spring.application.name=App
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.app.rsa.private-key-path= classpath:certs/private_key.pem
spring.app.rsa.public-key-path= classpath:certs/public_key.pem

# FILE: src/main/resources/application.properties
# Bật Virtual Threads (Tính năng "sát thủ" của Java 21+)
spring.threads.virtual.enabled=true

# Kết nối Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cấu hình Hibernate cho High-load
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true




# Kafka Config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Đảm bảo JSON có thể gửi qua Kafka
spring.kafka.producer.properties.spring.json.add.type.headers=true
# Đọc từ tin nhắn cũ nhất nếu là group mới
spring.kafka.consumer.auto-offset-reset=earliest
# Tin tưởng package để giải mã JSON

# Tin tưởng tất cả package khi giải mã JSON (Quan trọng cho Spring 4)
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Ép Consumer đọc từ tin nhắn cũ nhất nếu nó vừa mới khởi động

spring.main.allow-bean-definition-overriding=true









# --- Cấu hình Email (Mailtrap) ---
# Sửa lại đoạn này cho chính xác
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cấu hình RabbitMQ (Nếu bạn chạy Docker như Phase 5 mình hướng dẫn)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}









