spring.application.name=App
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_db
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.app.rsa.private-key-path= classpath:certs/private_key.pem
spring.app.rsa.public-key-path= classpath:certs/public_key.pem

# FILE: src/main/resources/application.properties
# Bật Virtual Threads (Tính năng "sát thủ" của Java 21+)
spring.threads.virtual.enabled=true

# Kết nối Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cấu hình Hibernate cho High-load
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true




# Kafka Config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Đảm bảo JSON có thể gửi qua Kafka
spring.kafka.producer.properties.spring.json.add.type.headers=true